services:
  localstack:
    image: localstack/localstack:3.5.0
    container_name: localstack_main
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,ec2,rds,elbv2,iam,autoscaling
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=0
      - LS_LOG=warn
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:15
    container_name: taobao_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=taobao
      - POSTGRES_PASSWORD=taobao123
      - POSTGRES_DB=taobao
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
